In [2]:
import numpy as np

In [14]:
a = np.array([1,2,3]) ;print(f"a=",a)
b = np.array([(1,2,3), (4,5,6)], dtype = int); print(f"b=",b)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype = float) ; print(f"c=",c)

a= [1 2 3]
b= [[1 2 3]
 [4 5 6]]
c= [[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


In [16]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
 np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [19]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [20]:
 np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [24]:
np.linspace(1,10,4,retstep =True)

(array([ 1.,  4.,  7., 10.]), 3.0)

In [25]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [26]:
 np.random.random((2,2))

array([[0.31202802, 0.07206415],
       [0.18460476, 0.81285049]])

In [38]:
np.random.poisson(2,100)

array([2, 2, 4, 3, 4, 4, 0, 1, 3, 2, 1, 1, 1, 4, 3, 3, 2, 2, 1, 1, 1, 1,
       2, 3, 2, 1, 2, 4, 0, 1, 0, 2, 2, 4, 1, 3, 3, 1, 4, 3, 4, 1, 4, 2,
       5, 2, 3, 2, 1, 3, 2, 1, 1, 3, 2, 1, 0, 3, 1, 1, 2, 2, 1, 1, 3, 1,
       2, 3, 1, 4, 1, 0, 2, 1, 7, 2, 0, 3, 2, 1, 1, 2, 3, 4, 3, 0, 0, 2,
       0, 0, 0, 2, 3, 3, 2, 3, 1, 3, 1, 4])

In [36]:
mu, sigma = 100, 10 # mean and standard deviation
s = np.random.normal(mu, sigma, (3,4))
print(s)

[[ 87.23286213 111.56071328  89.8723197   94.84452953]
 [107.96870935  93.12634096  94.44025074  87.85641985]
 [105.85121502 108.50927546  86.62203063 105.38871584]]


In [39]:
mu, sigma = 100, 10 # mean and standard deviation
s = np.random.normal(mu, sigma,100)
print(s)

[102.64116037 122.73345021  99.39674886  94.90189518 108.85688177
 107.23766482  89.64313427 103.73218835  90.40104088  87.80469584
  86.20125207  89.64563638  94.98784653  91.50719299  94.9057089
 102.16231596  78.71273185 104.91142339 102.42363437 104.44495939
 102.03047257 106.13095275  80.4731517   85.90905553  93.59536602
  95.6162339   96.83839243 112.01562659 101.42150644 107.22032555
  82.38189084  96.4412745  101.23591845 105.09990342 106.85683462
  94.14054245 103.2740522  114.11030218  89.85627599 103.21039052
 112.92599609 112.37613813  96.74107518  94.36716732  94.91354093
  91.30698454  98.3815779  101.94923867 109.59738188  88.87417567
 100.16411578 100.76653931  99.56708325  96.48130233  95.59133737
  91.16596085 107.21855708 104.82001326 124.13300053  96.05510161
 107.24838265 107.34512377  99.64523647  90.74936401  90.02485989
  92.89584808 112.08368486 102.00916535  99.35555726  86.10799682
  86.66419628  98.18996393 108.87885249  88.46284689 101.81731967
  98.098014

In [42]:
#Return a new array of given shape and type, without initializing entries
r= np.empty(3,2) 
print(r)

[ 3.33333333  6.66666667 10.        ]


In [44]:
a = np.array([1,2,3])
b = np.array([8,6,7])
print(f"addition  a+b={a+b}")
np.add(a,b)

addition  a+b=[ 9  8 10]


In [45]:
np.

array([ 9,  8, 10])

In [48]:
!pip install jupyter_contrib_nbextensions


[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip
